### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by hotaru1227** [LiamLian0727/USIS10K#1]
Hello,

Thank you for uploading your work. I attempted to run the code using the NWPU remote sensing dataset in COCO format, but I encountered some issues.

Could you please let me know when the dataset proposed in your work will be publicly available? Alternatively, could you provide the specific field settings?

I look forward to your response.

**Comment by LiamLian0727** [comment]
You can get our USIS10K dataset in [Baidu Disk](https://pan.baidu.com/s/1dsyRvGADZD43MwrNHlNIdw?pwd=icml) (pwd:icml) or [Google Drive](https://drive.google.com/file/d/1LdjLPaieWA4m8vLV6hEeMvt5wHnLg9gV/view?usp=sharing).

**Comment by LiamLian0727** [comment]
Thank you for supporting our work, and if you find our code and datasets useful, please cite us by giving our repository stars!

**Comment by hotaru1227** [comment]
Thank you for your reply and the open-source data.🌹🌹🌹
