### ISSUE TITLE
权重文件问题

### ISSUE THREAD

**Issue by akang-ai** [LiamLian0727/USIS10K#10]
![frame_0000](https://github.com/user-attachments/assets/5af47382-697a-4103-b3a2-78aaaf28be10)
为什么我在使用class_agniostic_model.pth的时候，显示有好多框，怎么跟论文中的显示不一样

**Comment by LiamLian0727** [comment]
In fact, the test module of mmdetection's inference generally sets the NMS first and filters inference results with lower confidence by a threshold (just as mask rcnn does), and if you're manually calling the weights, you can need to complete these modules on your own

**Comment by akang-ai** [comment]
那如果我要在我自己的数据集上得到像论文中的这些类似的图片，例如这样
![image](https://github.com/user-attachments/assets/6f63f0fc-f64f-4663-abb8-1ff3324e0e29)
我需要调整NMS和Io阈值为多少呢？
![image](https://github.com/user-attachments/assets/766dd156-c74b-4a92-bb1f-542536c29465)

**Comment by LiamLian0727** [comment]
Sorry, I may have misunderstood your object before. If you don't want the model to output bounding boxes, you may need to modify part of the source code yourself.

**Comment by LiamLian0727** [comment]
The images in my paper were generated by inference from a script I wrote myself, not mmdetection. There may be a way to output the images without the bounding box in mmdetection as well, you can visit the documentation on their website for help.
