### ISSUE TITLE
about paper

### ISSUE THREAD

**Issue by hotaru1227** [LiamLian0727/USIS10K#2]
Hello, thank you again for your work. Has the paper not been published yet? When will it be available?

**Comment by CaoJiahao2** [comment]
I'm also finding the pdf format paper, but I can't download it anywhere in the web.

**Comment by LiamLian0727** [comment]
You can download our paper by following this [link](https://openreview.net/pdf?id=snhurpZt63)

**Comment by hotaru1227** [comment]
Thank you so much 🌹🌹🌹
