### ISSUE TITLE
How to convert the train.json file to a single image corresponding to a single .json file, for example SA-1B dataset

### ISSUE THREAD

**Issue by sajdhak** [LiamLian0727/USIS10K#3]
![image](https://github.com/LiamLian0727/USIS10K/assets/173120266/24f6ecd3-85a7-4f28-86b6-94f375c8f031)

**Comment by LiamLian0727** [comment]
I think you need to write a simple script to do it yourself, the json files for the USIS10K dataset are in MS COCO format, which is very similar to the SA-1B dataset, all you can simply convert them between the two formats with a py script.

**Comment by LiamLian0727** [comment]
In addition, segmentations in USIS10K are stored via polygon format, if you need to convert them to RLE format, you can use the relevant tools in the pycocotools API (e.g. annToRLE function)
