### ISSUE TITLE
数据集的问题

### ISSUE THREAD

**Issue by Ryanye2000** [LiamLian0727/USIS10K#4]
![屏幕截图 2024-08-17 105230](https://github.com/user-attachments/assets/f3fecb29-7a85-4dcf-be93-cf022ab9d84f)
我是把我自己的图片加上xml格式的数据集用py脚本转换成了coco格式的，但是运行的时候一直提示图片里的内容，我觉得应该是数据集转换的json格式的问题，想问下作者有没有可以提供的转换脚本啊，或者是格式规范

**Comment by Ryanye2000** [comment]
[test_annotations.json](https://github.com/user-attachments/files/16643206/test_annotations.json)
这是我生成的json文件，如果有什么是导致这个问题的原因，就麻烦作者帮我看一下了，十分感谢

**Comment by Ryanye2000** [comment]
我还使用了代码中提供的voc的脚本，就是把bbox的四个点作为segmentation的那个处理了一遍，但是结果还是一样的no pos rois

**Comment by LiamLian0727** [comment]
I guess it might be the wrong bbox format, coco format in bounding box form is [top_left_x,top_left_y,w,h]

**Comment by Ryanye2000** [comment]
[multi_class_test_annotations.json](https://github.com/user-attachments/files/16643934/multi_class_t
![屏幕截图 2024-08-17 151946](https://github.com/user-attachments/assets/7f7b544f-fadc-446f-b7b9-005446f682c2)
est_annotations.json)
zhe'l这里我使用了您在代码中提供的转换脚本也就是pascal_voc.py，其中bbox的四个值如图就是xmin，ymin，w，h了，但是还是一样的错误

**Comment by Ryanye2000** [comment]
![屏幕截图 2024-08-17 154742](https://github.com/user-attachments/assets/eb245c6e-0aab-4036-acda-e998b3e84733)
![屏幕截图 2024-08-17 154754](https://github.com/user-attachments/assets/36127f02-bfdf-4a40-91d1-bb414fc9d99c)
上图是我的数据集的一条标注信息，下图是您的数据集的一条标注信息，我发现其中键值的顺序不太一样，我的第一个是segmentation信息。你的是id，这个会是报错的原因吗

**Comment by Ryanye2000** [comment]
我解决了，是dataset.py需要复写一下，感谢作者
