### ISSUE TITLE
配置完成，路径修改仍然许多报错

### ISSUE THREAD

**Issue by Lei0829** [LiamLian0727/USIS10K#8]
root@autodl-container-83e841b5cc-b278e822:~# bash tools/dist_train.sh project/our/configs/multiclass_usis_train.py 3
bash: tools/dist_train.sh: No such file or directory
root@autodl-container-83e841b5cc-b278e822:~# cd /autodl-fs/data/USIS10K-main/
root@autodl-container-83e841b5cc-b278e822:/autodl-fs/data/USIS10K-main# bash tools/dist_train.sh project/our/configs/multiclass_usis_train.py 3
/root/miniconda3/lib/python3.10/site-packages/torch/distributed/launch.py:181: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
11/03 00:04:30 - mmengine - INFO - 
------------------------------------------------------------
System environment:
    sys.platform: linux
    Python: 3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0]
    CUDA available: True
    MUSA available: False
    numpy_random_seed: 1007583564
    GPU 0,1,2: NVIDIA GeForce RTX 4090
    CUDA_HOME: /usr/local/cuda
    NVCC: Cuda compilation tools, release 11.8, V11.8.89
    GCC: gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
    PyTorch: 2.1.2+cu118
    PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.1.1 (Git Hash 64f6bcbcbab628e96f33a62c3e975f8535a7bde4)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.8
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.7
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-unused-private-field -Wno-aligned-allocation-unavailable -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.1.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

    TorchVision: 0.16.2+cu118
    OpenCV: 4.10.0
    MMEngine: 0.10.5

Runtime environment:
    dist_cfg: {'backend': 'nccl'}
    seed: 1007583564
    Distributed launcher: pytorch
    Distributed training: True
    GPU number: 3
------------------------------------------------------------

11/03 00:04:30 - mmengine - INFO - Config:
CLASSES = dict(classes=[
    'wrecks/ruins',
    'fish',
    'reefs',
    'aquatic plants',
    'human divers',
    'robots',
    'sea-floor',
])
auto_scale_lr = dict(base_batch_size=2, enable=False)
backend_args = None
base_lr = 0.0001
batch_augments = [
    dict(
        img_pad_value=0,
        mask_pad_value=0,
        pad_mask=True,
        pad_seg=False,
        size=(
            1024,
            1024,
        ),
        type='BatchFixedSizePad'),
]
batch_size = 2
crop_size = (
    1024,
    1024,
)
data_preprocessor = dict(
    batch_augments=[
        dict(
            img_pad_value=0,
            mask_pad_value=0,
            pad_mask=True,
            pad_seg=False,
            size=(
                1024,
                1024,
            ),
            type='BatchFixedSizePad'),
    ],
    bgr_to_rgb=True,
    mean=[
        123.675,
        116.28,
        103.53,
    ],
    pad_mask=True,
    pad_size_divisor=32,
    std=[
        58.395,
        57.120000000000005,
        57.375,
    ],
    type='DetDataPreprocessor')
data_root = '/autodl-fs/data/USIS10K-main/data/USIS10K'
dataset_type = 'MultiClassUSIS10KInsSegDataset'
find_unused_parameters = True
indices = None
launcher = 'pytorch'
max_epochs = 24
model = dict(
    backbone=dict(extra_config=dict(image_size=1024)),
    data_preprocessor=dict(
        batch_augments=[
            dict(
                img_pad_value=0,
                mask_pad_value=0,
                pad_mask=True,
                pad_seg=False,
                size=(
                    1024,
                    1024,
                ),
                type='BatchFixedSizePad'),
        ],
        bgr_to_rgb=True,
        mean=[
            123.675,
            116.28,
            103.53,
        ],
        pad_mask=True,
        pad_size_divisor=32,
        std=[
            58.395,
            57.120000000000005,
            57.375,
        ],
        type='DetDataPreprocessor'),
    decoder_freeze=True,
    roi_head=dict(bbox_head=dict(num_classes=7)),
    shared_image_embedding=dict(extra_config=dict(image_size=1024)),
    train_cfg=dict(rcnn=dict(mask_size=(
        1024,
        1024,
    ))))
num_classes = 7
num_workers = 8
optim_wrapper = dict(
    dtype='float16',
    optimizer=dict(lr=0.0001, type='AdamW', weight_decay=0.05),
    type='AmpOptimWrapper')
param_scheduler = [
    dict(begin=0, by_epoch=False, end=50, start_factor=0.001, type='LinearLR'),
    dict(
        begin=0,
        by_epoch=True,
        end=24,
        gamma=0.1,
        milestones=[
            15,
            21,
        ],
        type='MultiStepLR'),
]
persistent_workers = True
test_cfg = dict(type='TestLoop')
test_dataloader = dict(
    batch_size=2,
    dataset=dict(
        ann_file=
        '/autodl-fs/data/USIS10K-main/data/USIS10K/multi_class_annotations/multi_class_test_annotations.json',
        backend_args=None,
        data_prefix=dict(img='test'),
        data_root='/autodl-fs/data/USIS10K-main/data/USIS10K',
        indices=None,
        metainfo=dict(classes=[
            'wrecks/ruins',
            'fish',
            'reefs',
            'aquatic plants',
            'human divers',
            'robots',
            'sea-floor',
        ]),
        pipeline=[
            dict(backend_args=None, to_float32=True, type='LoadImageFromFile'),
            dict(keep_ratio=True, scale=(
                1024,
                1024,
            ), type='Resize'),
            dict(
                pad_val=dict(img=(
                    103.53,
                    116.28,
                    123.675,
                ), masks=0),
                size=(
                    1024,
                    1024,
                ),
                type='Pad'),
            dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
            dict(
                meta_keys=(
                    'img_id',
                    'img_path',
                    'ori_shape',
                    'img_shape',
                    'pad_shape',
                    'scale_factor',
                ),
                type='PackDetInputs'),
        ],
        test_mode=True,
        type='MultiClassUSIS10KInsSegDataset'),
    drop_last=False,
    num_workers=8,
    persistent_workers=True,
    sampler=dict(shuffle=False, type='DefaultSampler'))
test_evaluator = dict(
    ann_file=
    '/autodl-fs/data/USIS10K-main/data/USIS10K/autodl-fs/data/USIS10K-main/data/USIS10K/multi_class_annotations/multi_class_test_annotations.json',
    backend_args=None,
    format_only=False,
    metric=[
        'bbox',
        'segm',
    ],
    type='CocoMetric')
test_pipeline = [
    dict(backend_args=None, to_float32=True, type='LoadImageFromFile'),
    dict(keep_ratio=True, scale=(
        1024,
        1024,
    ), type='Resize'),
    dict(
        pad_val=dict(img=(
            103.53,
            116.28,
            123.675,
        ), masks=0),
        size=(
            1024,
            1024,
        ),
        type='Pad'),
    dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
    dict(
        meta_keys=(
            'img_id',
            'img_path',
            'ori_shape',
            'img_shape',
            'pad_shape',
            'scale_factor',
        ),
        type='PackDetInputs'),
]
train_cfg = dict(max_epochs=24, type='EpochBasedTrainLoop', val_interval=3)
train_dataloader = dict(
    batch_size=2,
    dataset=dict(
        ann_file=
        '/autodl-fs/data/USIS10K-main/data/USIS10K/multi_class_annotations/multi_class_train_annotations.json',
        backend_args=None,
        data_prefix=dict(img='train'),
        data_root='/autodl-fs/data/USIS10K-main/data/USIS10K',
        indices=None,
        metainfo=dict(classes=[
            'wrecks/ruins',
            'fish',
            'reefs',
            'aquatic plants',
            'human divers',
            'robots',
            'sea-floor',
        ]),
        pipeline=[
            dict(backend_args=None, to_float32=True, type='LoadImageFromFile'),
            dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
            dict(prob=0.5, type='RandomFlip'),
            dict(
                keep_ratio=True,
                ratio_range=(
                    0.1,
                    2.0,
                ),
                resize_type='Resize',
                scale=(
                    1024,
                    1024,
                ),
                type='RandomResize'),
            dict(
                allow_negative_crop=True,
                crop_size=(
                    1024,
                    1024,
                ),
                crop_type='absolute',
                recompute_bbox=True,
                type='RandomCrop'),
            dict(
                by_mask=True,
                min_gt_bbox_wh=(
                    1e-05,
                    1e-05,
                ),
                type='FilterAnnotations'),
            dict(type='PackDetInputs'),
        ],
        type='MultiClassUSIS10KInsSegDataset'),
    num_workers=8,
    persistent_workers=True,
    sampler=dict(shuffle=True, type='DefaultSampler'))
train_pipeline = [
    dict(backend_args=None, to_float32=True, type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
    dict(prob=0.5, type='RandomFlip'),
    dict(
        keep_ratio=True,
        ratio_range=(
            0.1,
            2.0,
        ),
        resize_type='Resize',
        scale=(
            1024,
            1024,
        ),
        type='RandomResize'),
    dict(
        allow_negative_crop=True,
        crop_size=(
            1024,
            1024,
        ),
        crop_type='absolute',
        recompute_bbox=True,
        type='RandomCrop'),
    dict(
        by_mask=True,
        min_gt_bbox_wh=(
            1e-05,
            1e-05,
        ),
        type='FilterAnnotations'),
    dict(type='PackDetInputs'),
]
val_cfg = dict(type='ValLoop')
val_dataloader = dict(
    batch_size=2,
    dataset=dict(
        ann_file=
        '/autodl-fs/data/USIS10K-main/data/USIS10K/multi_class_annotations/multi_class_val_annotations.json',
        backend_args=None,
        data_prefix=dict(img='val'),
        data_root='/autodl-fs/data/USIS10K-main/data/USIS10K',
        indices=None,
        metainfo=dict(classes=[
            'wrecks/ruins',
            'fish',
            'reefs',
            'aquatic plants',
            'human divers',
            'robots',
            'sea-floor',
        ]),
        pipeline=[
            dict(backend_args=None, to_float32=True, type='LoadImageFromFile'),
            dict(keep_ratio=True, scale=(
                1024,
                1024,
            ), type='Resize'),
            dict(
                pad_val=dict(img=(
                    103.53,
                    116.28,
                    123.675,
                ), masks=0),
                size=(
                    1024,
                    1024,
                ),
                type='Pad'),
            dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
            dict(
                meta_keys=(
                    'img_id',
                    'img_path',
                    'ori_shape',
                    'img_shape',
                    'pad_shape',
                    'scale_factor',
                ),
                type='PackDetInputs'),
        ],
        test_mode=True,
        type='MultiClassUSIS10KInsSegDataset'),
    drop_last=False,
    num_workers=8,
    persistent_workers=True,
    sampler=dict(shuffle=False, type='DefaultSampler'))
val_evaluator = dict(
    ann_file=
    '/autodl-fs/data/USIS10K-main/data/USIS10K/autodl-fs/data/USIS10K-main/data/USIS10K/multi_class_annotations/multi_class_val_annotations.json',
    backend_args=None,
    format_only=False,
    metric=[
        'bbox',
        'segm',
    ],
    type='CocoMetric')
work_dir = '/autodl-fs/data/USIS10K-main/work_dirs/USIS10KDataset/huge'
y_base_ = [
    'anchor_net.py',
]

Traceback (most recent call last):
  File "/autodl-fs/data/USIS10K-main/tools/train.py", line 124, in <module>
    main()
  File "/autodl-fs/data/USIS10K-main/tools/train.py", line 113, in main
    runner = Runner.from_cfg(cfg)
  File "/root/miniconda3/lib/python3.10/site-packages/mmengine/runner/runner.py", line 462, in from_cfg
    runner = cls(
  File "/root/miniconda3/lib/python3.10/site-packages/mmengine/runner/runner.py", line 429, in __init__
    self.model = self.build_model(model)
  File "/root/miniconda3/lib/python3.10/site-packages/mmengine/runner/runner.py", line 836, in build_model
    model = MODELS.build(model)
  File "/root/miniconda3/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/root/miniconda3/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/root/miniconda3/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 72, in build_from_cfg
    raise KeyError(
KeyError: '`cfg` or `default_args` must contain the key "type", but got {\'data_preprocessor\': {\'type\': \'DetDataPreprocessor\', \'mean\': [123.675, 116.28, 103.53], \'std\': [58.395, 57.120000000000005, 57.375], \'bgr_to_rgb\': True, \'pad_mask\': True, \'pad_size_divisor\': 32, \'batch_augments\': [{\'type\': \'BatchFixedSizePad\', \'size\': (1024, 1024), \'img_pad_value\': 0, \'pad_mask\': True, \'mask_pad_value\': 0, \'pad_seg\': False}]}, \'decoder_freeze\': True, \'shared_image_embedding\': {\'extra_config\': {\'image_size\': 1024}}, \'backbone\': {\'extra_config\': {\'image_size\': 1024}}, \'roi_head\': {\'bbox_head\': {\'num_classes\': 7}}, \'train_cfg\': {\'rcnn\': {\'mask_size\': (1024, 1024)}}}\nNone'
Traceback (most recent call last):
  File "/autodl-fs/data/USIS10K-main/tools/train.py", line 124, in <module>
    main()
  File "/autodl-fs/data/USIS10K-main/tools/train.py", line 113, in main
    runner = Runner.from_cfg(cfg)
  File "/root/miniconda3/lib/python3.10/site-packages/mmengine/runner/runner.py", line 462, in from_cfg
    runner = cls(
  File "/root/miniconda3/lib/python3.10/site-packages/mmengine/runner/runner.py", line 429, in __init__
    self.model = self.build_model(model)
  File "/root/miniconda3/lib/python3.10/site-packages/mmengine/runner/runner.py", line 836, in build_model
    model = MODELS.build(model)
  File "/root/miniconda3/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/root/miniconda3/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/root/miniconda3/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 72, in build_from_cfg
    raise KeyError(
KeyError: '`cfg` or `default_args` must contain the key "type", but got {\'data_preprocessor\': {\'type\': \'DetDataPreprocessor\', \'mean\': [123.675, 116.28, 103.53], \'std\': [58.395, 57.120000000000005, 57.375], \'bgr_to_rgb\': True, \'pad_mask\': True, \'pad_size_divisor\': 32, \'batch_augments\': [{\'type\': \'BatchFixedSizePad\', \'size\': (1024, 1024), \'img_pad_value\': 0, \'pad_mask\': True, \'mask_pad_value\': 0, \'pad_seg\': False}]}, \'decoder_freeze\': True, \'shared_image_embedding\': {\'extra_config\': {\'image_size\': 1024}}, \'backbone\': {\'extra_config\': {\'image_size\': 1024}}, \'roi_head\': {\'bbox_head\': {\'num_classes\': 7}}, \'train_cfg\': {\'rcnn\': {\'mask_size\': (1024, 1024)}}}\nNone'
Traceback (most recent call last):
  File "/autodl-fs/data/USIS10K-main/tools/train.py", line 124, in <module>
    main()
  File "/autodl-fs/data/USIS10K-main/tools/train.py", line 113, in main
    runner = Runner.from_cfg(cfg)
  File "/root/miniconda3/lib/python3.10/site-packages/mmengine/runner/runner.py", line 462, in from_cfg
    runner = cls(
  File "/root/miniconda3/lib/python3.10/site-packages/mmengine/runner/runner.py", line 429, in __init__
    self.model = self.build_model(model)
  File "/root/miniconda3/lib/python3.10/site-packages/mmengine/runner/runner.py", line 836, in build_model
    model = MODELS.build(model)
  File "/root/miniconda3/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/root/miniconda3/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/root/miniconda3/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 72, in build_from_cfg
    raise KeyError(
KeyError: '`cfg` or `default_args` must contain the key "type", but got {\'data_preprocessor\': {\'type\': \'DetDataPreprocessor\', \'mean\': [123.675, 116.28, 103.53], \'std\': [58.395, 57.120000000000005, 57.375], \'bgr_to_rgb\': True, \'pad_mask\': True, \'pad_size_divisor\': 32, \'batch_augments\': [{\'type\': \'BatchFixedSizePad\', \'size\': (1024, 1024), \'img_pad_value\': 0, \'pad_mask\': True, \'mask_pad_value\': 0, \'pad_seg\': False}]}, \'decoder_freeze\': True, \'shared_image_embedding\': {\'extra_config\': {\'image_size\': 1024}}, \'backbone\': {\'extra_config\': {\'image_size\': 1024}}, \'roi_head\': {\'bbox_head\': {\'num_classes\': 7}}, \'train_cfg\': {\'rcnn\': {\'mask_size\': (1024, 1024)}}}\nNone'
[2024-11-03 00:04:36,039] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 1319) of binary: /root/miniconda3/bin/python
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-11-03_00:04:36
  host      : autodl-container-83e841b5cc-b278e822
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1320)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-11-03_00:04:36
  host      : autodl-container-83e841b5cc-b278e822
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 1321)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-11-03_00:04:36
  host      : autodl-container-83e841b5cc-b278e822
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1319)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
root@autodl-container-83e841b5cc-b278e822:/autodl-fs/data/USIS10K-main#

**Comment by LiamLian0727** [comment]
In fact, your problem is due to the following error, which may be caused by a wrong modification of the config file, resulting in mmdetection not detecting a certain class of configuration module
```
KeyError: 'cfg or default_args must contain the key "type", but got {'data_preprocessor': {'type': 'DetDataPreprocessor', 'mean': [123.675, 116.28, 103.53], 'std': [58.395, 57.120000000000005, 57.375], 'bgr_to_rgb': True, 'pad_mask': True, 'pad_size_divisor': 32, 'batch_augments': [{'type': 'BatchFixedSizePad', 'size': (1024, 1024), 'img_pad_value': 0, 'pad_mask': True, 'mask_pad_value': 0, 'pad_seg': False}]}, 'decoder_freeze': True, 'shared_image_embedding': {'extra_config': {'image_size': 1024}}, 'backbone': {'extra_config': {'image_size': 1024}}, 'roi_head': {'bbox_head': {'num_classes': 7}}, 'train_cfg': {'rcnn': {'mask_size': (1024, 1024)}}}\nNone'
```

**Comment by LiamLian0727** [comment]
If you can provide me with the config file you are using, I can help you further!
